
[colors.primary]
background = "#11121D"
foreground = "#A0A8CD"
dim_foreground = "#787C99"
bright_foreground = "#ACB0D0"


[colors.cursor]
text = "#11121D"
cursor = "#A0A8CD"


[colors.vi_mode_cursor]
text = "#11121D"
cursor = "#7AA2F7"


[colors.selection]
text = "#11121D"
background = "#A0A8CD"


[colors.search.matches]
foreground = "#11121D"
background = "#787C99"

[colors.search.focused_match]
foreground = "#11121D"
background = "#9ECE6A"


[colors.footer_bar]
foreground = "#11121D"
background = "#787C99"


[colors.hints.start]
foreground = "#11121D"
background = "#E0AF68"

[colors.hints.end]
foreground = "#11121D"
background = "#787C99"


# ================================
# Normal colors
# ================================
[colors.normal]
black   = "#32344A"
red     = "#F7768E"
green   = "#9ECE6A"
yellow  = "#E0AF68"
blue    = "#7AA2F7"
magenta = "#AD8EE6"
cyan    = "#449DAB"
white   = "#787C99"


# ================================
# Bright colors
# ================================
[colors.bright]
black   = "#444B6A"
red     = "#FF7A93"
green   = "#B9F27C"
yellow  = "#FF9E64"
blue    = "#7DA6FF"
magenta = "#BB9AF7"
cyan    = "#0DB9D7"
white   = "#ACB0D0"


# ================================
# Dim colors (derived, soft)
# ================================
[colors.dim]
black   = "#32344A"
red     = "#F7768E"
green   = "#9ECE6A"
yellow  = "#E0AF68"
blue    = "#7AA2F7"
magenta = "#AD8EE6"
cyan    = "#449DAB"
white   = "#787C99"


# ================================
# Indexed colors (optional)
# ================================
[[colors.indexed_colors]]
index = 16
color = "#FF9E64"

[[colors.indexed_colors]]
index = 17
color = "#F7768E"

